services:
  # Base de datos PostgreSQL
  - type: pserv
    name: ecommerce-db
    env: docker
    region: oregon
    plan: free
    databases:
      - name: ecommerce_prod
        user: ecommerce_user

  # Aplicación web
  - type: web
    name: ecommerce-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    # Variables de entorno - configurar desde el dashboard de Render
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 480
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: PROJECT_NAME
        value: "Ecommerce API"
      - key: VERSION
        value: "1.0.0"
      - key: DESCRIPTION
        value: "Backend API for Ecommerce platform"
      - key: API_V1_STR
        value: "/api/v1"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: DEFAULT_PAGE_SIZE
        value: 20
      - key: MAX_PAGE_SIZE
        value: 100
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_FOLDER
        value: uploads
      # Nota: ADMIN_EMAIL, ADMIN_PASSWORD y BACKEND_CORS_ORIGINS
      # deben configurarse manualmente desde el dashboard de Render
    # Comando de construcción
    buildCommand: echo "Building with Docker"
    # Comando de inicio con puerto dinámico de Render
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4
